EDIT | 134

diff --git a/.github/workflows/gpt-code-review.yml b/.github/workflows/gpt-code-review.yml
--- a/.github/workflows/gpt-code-review.yml
+++ b/.github/workflows/gpt-code-review.yml
@@ -62,26 +62,29 @@ jobs:
           comment_on_review=$(echo "$comment" | jq -r '.body')
           echo "comment_on_review ------->" $comment_on_review
 
-          echo 'Extracted rating 1 --->' $comment_on_review
-          echo 'Extracted rating 2 --->' ${comment_on_review:0:13}
+          echo 'Extracted rating 1 --->' ${comment_on_review:0:13}
+
+          rating=$(echo "$comment_on_review" | grep -o -P 'Rating: \K[0-9]+(?=/10)')
+
+          echo 'Extracted rating 2 --->' $rating
 
       # - name: Rating result
-      #   run: |
-      #     # rating=$(echo "$comment_on_review" | grep -o -P 'Rating: \K[0-9]+(?=/10)')
-      #     # rating=$(echo "$comment_on_review" | grep -o -P 'Rating:')
+      # run: |
+      #   # rating=$(echo "$comment_on_review" | grep -o -P 'Rating: \K[0-9]+(?=/10)')
+      #   # rating=$(echo "$comment_on_review" | grep -o -P 'Rating:')
 
-      #     # echo 'Extracted rating 1 --->' $comment_on_review
-      #     # echo 'Extracted rating 2 --->' $comment_on_review:0:13
-      #     # echo 'Extracted rating --->' $rating
+      #   # echo 'Extracted rating 1 --->' $comment_on_review
+      #   # echo 'Extracted rating 2 --->' $comment_on_review:0:13
+      #   # echo 'Extracted rating --->' $rating
 
-      #     # # Conditional check to determine the workflow outcome
-      #     # if [ "$rating" -le 2 ]; then
-      #     #   echo "Rating is $rating/10, which is considered as failure."
-      #     #   exit 1
-      #     # elif [ "$rating" -ge 3 ]; then
-      #     #   echo "Rating is $rating/10, proceeding with success."
-      #     # else
-      #     #   echo "Unexpected rating value, proceeding with caution."
+      #   # # Conditional check to determine the workflow outcome
+      #   # if [ "$rating" -le 2 ]; then
+      #   #   echo "Rating is $rating/10, which is considered as failure."
+      #   #   exit 1
+      #   # elif [ "$rating" -ge 3 ]; then
+      #   #   echo "Rating is $rating/10, proceeding with success."
+      #   # else
+      #   #   echo "Unexpected rating value, proceeding with caution."
 
       # - name: Check condition and possibly fail
       #   run: |
