EDIT | 122

diff --git a/.github/workflows/gpt-code-review.yml b/.github/workflows/gpt-code-review.yml
--- a/.github/workflows/gpt-code-review.yml
+++ b/.github/workflows/gpt-code-review.yml
@@ -49,18 +49,24 @@ jobs:
       - name: Add a comment
         run: |
           cat code_suggestions.txt
-          escaped_comments=$(echo "$(cat code_suggestions.txt)" | jq -s -R -r @json)
-          curl -L \
+          comment_on_code_changes=$(echo "$(cat code_suggestions.txt)" | jq -s -R -r @json)
+
+          comment=$(curl -L \
             -X POST \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments" \
-            -d "{\"body\": $escaped_comments}"
+            -d "{\"body\": $comment_on_code_changes}")
 
-      - name: Fail the workflow
-        run: |
-          echo "Manually failing the workflow"
-          exit 1
+          echo "comment ------->" $comment
+
+      # - name: Check condition and possibly fail
+      #   run: |
+      #     if [[ $CONDITION == 'true' ]]; then
+      #       echo "Condition met, failing the workflow"
+      #       exit 1
+      #     else
+      #       echo "Condition not met, continuing"
 
 # ------------------------------------------
