EDIT | 135

diff --git a/.github/workflows/gpt-code-review.yml b/.github/workflows/gpt-code-review.yml
--- a/.github/workflows/gpt-code-review.yml
+++ b/.github/workflows/gpt-code-review.yml
@@ -68,6 +68,16 @@ jobs:
 
           echo 'Extracted rating 2 --->' $rating
 
+          if [ "$rating" -le 2 ]; then
+          echo "Rating is $rating/10, which is considered as failure."
+          exit 1
+          elif [ "$rating" -ge 3 ]; then
+            echo "Rating is $rating/10, proceeding with success."
+          else
+            echo "Unexpected rating value, proceeding with caution."
+          fi
+            echo Done!!!
+
       # - name: Rating result
       # run: |
       #   # rating=$(echo "$comment_on_review" | grep -o -P 'Rating: \K[0-9]+(?=/10)')
